### ISSUE TITLE
Adding Members Check In Spot

### ISSUE THREAD

**Issue by ztglass** [ztglass/IT168_workshop#1]
Updating this issue to serve as a "check in" spot to add each member

Members added:
- [x] Kenneth
- [x] Owen
- [x] Sivani
- [x] Aidan
- [x] Ayden
- [x] Mark

**Comment by ztglass** [comment]
Add a comment to this issue and once I have you added, I'll check you off the list :)

**Comment by mmilan331** [comment]
W00t

**Comment by achefn1** [comment]
It's a me

**Comment by AydenVacca** [comment]
Hey

**Comment by okeene02** [comment]
Hello :-)

**Comment by SilentKB3** [comment]
Aloha

**Comment by ztglass** [comment]
Added Savanis Code. Closing issue
